# Generated by Django 4.1.5 on 2023-02-12 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subject",
            old_name="s_detail",
            new_name="S_detail",
        ),
        migrations.RenameField(
            model_name="subject",
            old_name="s_teacher",
            new_name="S_teacher",
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.TextField()),
                (
                    "student_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.subject",
                    ),
                ),
            ],
        ),
    ]
