# Generated by Django 4.1.5 on 2023-04-20 16:19

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subject",
            old_name="s_detail",
            new_name="S_detail",
        ),
        migrations.RenameField(
            model_name="subject",
            old_name="s_teacher",
            new_name="S_teacher",
        ),
        migrations.AddField(
            model_name="subject",
            name="post_id",
            field=models.ManyToManyField(
                blank=True, related_name="postsub", to="database.subject"
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="pre_id",
            field=models.ManyToManyField(
                blank=True, related_name="presub", to="database.subject"
            ),
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.TextField()),
                (
                    "student_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.subject",
                    ),
                ),
                (
                    "student_temp",
                    models.ManyToManyField(
                        blank=True, related_name="student_temp", to="database.subject"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("lft", models.PositiveIntegerField(db_index=True, editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="database.skill",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.subject",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
