# Generated by Django 4.1.5 on 2023-04-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0002_rename_s_detail_subject_s_detail_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="student_id",
        ),
        migrations.RemoveField(
            model_name="student",
            name="student_subject",
        ),
        migrations.RemoveField(
            model_name="student",
            name="student_temp",
        ),
        migrations.AddField(
            model_name="student",
            name="enrolled_subjects",
            field=models.ManyToManyField(to="database.subject"),
        ),
        migrations.AddField(
            model_name="student",
            name="user_id",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
