# Generated by Django 4.1.5 on 2023-02-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0002_rename_s_detail_subject_s_detail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="student_temp",
            field=models.ManyToManyField(
                blank=True, related_name="student_temp", to="database.subject"
            ),
        ),
    ]
