# Generated by Django 4.1.5 on 2023-04-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0003_remove_student_student_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="term",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
