# Generated by Django 4.1.5 on 2023-04-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0004_subject_term"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="same_id",
            field=models.ManyToManyField(
                blank=True, related_name="samesub", to="database.subject"
            ),
        ),
    ]
