# Generated by Django 4.1.5 on 2023-04-23 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0005_subject_same_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="pare",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children_of",
                to="database.subject",
            ),
        ),
    ]
